# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 09:30
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('cs308_restaurant_app', '0002_botstatus_bottablematch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bottablematch',
            old_name='table_num',
            new_name='order_num',
        ),
        migrations.RemoveField(
            model_name='botstatus',
            name='id',
        ),
        migrations.AddField(
            model_name='bottablematch',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 29, 9, 30, 1, 792900, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='dish_num',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botstatus',
            name='bot_num',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='bottablematch',
            name='delivered_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
