# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 16:25
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308_restaurant_app', '0003_auto_20160329_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='botstatus',
            name='curr_dir',
            field=models.IntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botstatus',
            name='next_x',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botstatus',
            name='next_y',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottablematch',
            name='order_position',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='botstatus',
            name='bot_num',
            field=models.IntegerField(primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
    ]
