# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-06 05:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cs308_restaurant_app', '0004_auto_20160405_1625'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botstatus',
            name='curr_dir',
        ),
        migrations.AddField(
            model_name='bottablematch',
            name='delivery_status',
            field=models.BooleanField(default=False),
        ),
    ]
